name: deploy

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    name: deploy

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: docker build . --build-arg BUILD_MODE=production -t radiodb-viewer

    - run: >
        mkdir -p ~/.ssh
        && echo "$SSH_KEY" > ~/.ssh/id_ed25519
        && chmod 600  ~/.ssh/id_ed25519
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}

    - run: docker save radiodb-viewer | ssh -oStrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST 'docker load'
      env:
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}

    - run: ssh -oStrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "echo \"$COMPOSE\" | docker-compose -p radiodb-viewer -f - up -d"
      env:
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        COMPOSE: |
          version: '3.7'
          services:
            main:
              read_only: yes
              restart: always
              image: radiodb-viewer
              volumes:
              - /etc/timezone:/etc/timezone:ro
              - /etc/localtime:/etc/localtime:ro
              - /ch/radiodb-viewer:/data
              ports:
              - 172.67.1.0:7446:7446
